print(pcall(function() error("boom") end))
print(pcall(function() error({code = 42}) end))
print(pcall(function() return 1 + nil end))
print(pcall(function() local t = nil; return t.x end))
print(pcall(function() local t = nil; t.x = 1 end))
print(pcall(function() return #nil end))
print(pcall(function() return ("x")() end))
print(pcall(function() return 1 < "a" end))
local ok, err = pcall(function() error("msg", 0) end)
print(ok, err)
print(xpcall(function() error("xp") end, function(e) return "handled:" .. e end))
